build:
	csc Program.cs Converter.cs testingClassStudents.cs testingClassConverter.cs Student.cs Group.cs
clear:
	rm -rf Program.exe
permissions:
	chmod +x ./Program.exe
run: build permissions
	./Program.exe
